/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hotel.management.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

public class CustomerCheckIn extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
   
    String Bed="";
    
    String Room_Num="";
    String Gender;
    
    
    public void Referesh()
    {
        FullName.setText("");
        PhoneNo.setText("");
        Nationality.setText("");
        Email.setText("");
        Id_Proof.setText("");
        Address.setText("");
        //Check_In_Date.setText("");
        Price.setText("");
        
       
}
    
    public CustomerCheckIn() {
        initComponents();
    }
        private void Bed() {
        
            String sql = "select*from addcustomer";
               try {
                     pst = conn.prepareStatement(sql);
                     rs = pst.executeQuery();
                     while(rs.next()) {
                     // Bed_type.addItem(rs.getString("Bed"));
            }
        }
         catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Empety list" +e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        FullName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PhoneNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Nationality = new javax.swing.JTextField();
        Genders = new javax.swing.JLabel();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        Others = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Id_Proof = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Price = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Clear = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Allote_Room = new javax.swing.JButton();
        BedTyp = new javax.swing.JTextField();
        Room_Types = new javax.swing.JTextField();
        RoomNo = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Customer Registration & Check IN.png"))); // NOI18N
        jLabel1.setText("customer Check In");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 439, 83));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, 32, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 164, 350, -1));

        FullName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(FullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 204, 350, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Phone No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 259, 350, -1));

        PhoneNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(PhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 299, 350, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Nationality");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 345, 350, -1));

        Nationality.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(Nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 385, 350, 30));

        Genders.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Genders.setText("Gender");
        getContentPane().add(Genders, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 431, 350, -1));

        buttonGroup1.add(Male);
        Male.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Male.setText("Male");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });
        getContentPane().add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 471, -1, -1));

        buttonGroup1.add(Female);
        Female.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Female.setText("Female");
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });
        getContentPane().add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 471, -1, -1));

        buttonGroup1.add(Others);
        Others.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Others.setText("Others");
        getContentPane().add(Others, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 471, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 524, 350, -1));

        Email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 569, 350, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Id Proof");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 164, 350, -1));

        Id_Proof.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(Id_Proof, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 204, 350, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 259, 350, -1));

        Address.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });
        getContentPane().add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 299, 350, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Check In Date (Today)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 345, 350, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Bed");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(874, 164, 350, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Room Type");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(874, 259, 350, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Room No.");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(874, 345, 350, -1));

        Price.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(874, 472, 350, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Price");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(874, 431, 350, -1));

        Clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Clear.setForeground(new java.awt.Color(153, 51, 0));
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1052, 520, 131, -1));

        Back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(153, 51, 0));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 570, 152, -1));

        Allote_Room.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Allote_Room.setForeground(new java.awt.Color(153, 51, 0));
        Allote_Room.setText("Allote Room");
        Allote_Room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Allote_RoomActionPerformed(evt);
            }
        });
        getContentPane().add(Allote_Room, new org.netbeans.lib.awtextra.AbsoluteConstraints(874, 520, 152, -1));
        getContentPane().add(BedTyp, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 200, 350, 30));

        Room_Types.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room_TypesActionPerformed(evt);
            }
        });
        getContentPane().add(Room_Types, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 350, 30));
        getContentPane().add(RoomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 390, 290, 30));

        Search.setBackground(new java.awt.Color(255, 255, 255));
        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search.png"))); // NOI18N
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 390, 50, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Admin.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        Home dash = new Home();
          dash.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Allote_RoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Allote_RoomActionPerformed
        //Gender Selection from radio buttons:
        if (Male.isSelected()==true){
            Gender="Male";
        } 
        else if (Female.isSelected()==true){
            Gender="Female";
        }
        else if (Others.isSelected()==true){
            Gender="Others";
        }
        
        String Name=FullName.getText();
        String Phone = PhoneNo.getText();
        String Nationalitys = Nationality.getText();
        String Emails = Email.getText();
        String Id = Id_Proof.getText();
        String Addresss= Address.getText();
        String Bed= BedTyp.getText();
        String Room_Type= Room_Types.getText();
        String Room_No= RoomNo.getText();
        
        SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MM-dd");
        String Dob = sdf.format(Check_In_Date.getDate());
        //String Dob = DateofbirthAP.getDate().toString();
        String Prices = Price.getText();
       // String Adhar = AadharAP.getText();
        
        System.out.println(Dob);
        String sql =("INSERT INTO customercheckin VALUES("+"'"+Name+"'"+","+Phone+",'"+Nationalitys+"'"+","+"'"+Gender+"'"+","+"'"+Emails+"'"+","+"'"+Id+"'"+","+"'"+Addresss+"'"+","+"'"+Dob+"'"+","+"'"+Bed+"'"+","+"'"+Room_Type+"'"+","+Room_No+","+Prices+")");
       System.out.println(sql);
        
        
        
         try{
           Connection c = Login.getLogin();
            Statement s = c.createStatement();
            s.execute(sql);
           s.execute("commit");
           
           JOptionPane.showMessageDialog(null,"Room Alloted Successfully");
           this.dispose();
           new CustomerCheckIn().setVisible(true);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"This Room is NOt Availables");
        }

    }//GEN-LAST:event_Allote_RoomActionPerformed

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        
    }//GEN-LAST:event_MaleActionPerformed

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
      
    }//GEN-LAST:event_FemaleActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        FullName.setText("");
        PhoneNo.setText("");
        Nationality.setText("");
        Email.setText("");
        Id_Proof.setText("");
        Address.setText("");
        BedTyp.setText("");
        RoomNo.setText("");
        Price.setText("");
        Room_Types.setText("");

    }//GEN-LAST:event_ClearActionPerformed

    private void Room_TypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room_TypesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Room_TypesActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        try{
           Class.forName("com.mysql.jdbc.Driver");
           //establish connection
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3309/hotel","root","rajan");
           Statement statement = con.createStatement();
           ResultSet rs=statement.executeQuery("Select* from available_room where Room_no="+Integer.parseInt(RoomNo.getText()));
           rs.next();
           BedTyp.setText(rs.getString(3));
           Room_Types.setText(rs.getString(2));
           Price.setText(rs.getString(4));
           
           
           
           
           
           
       }
       catch(SQLException | ClassNotFoundException e){
           JOptionPane.showMessageDialog(null,e);
       }
    }//GEN-LAST:event_SearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JButton Allote_Room;
    private javax.swing.JButton Back;
    private javax.swing.JTextField BedTyp;
    private javax.swing.JButton Clear;
    private javax.swing.JTextField Email;
    private javax.swing.JRadioButton Female;
    private javax.swing.JTextField FullName;
    private javax.swing.JLabel Genders;
    private javax.swing.JTextField Id_Proof;
    private javax.swing.JRadioButton Male;
    private javax.swing.JTextField Nationality;
    private javax.swing.JRadioButton Others;
    private javax.swing.JTextField PhoneNo;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField RoomNo;
    private javax.swing.JTextField Room_Types;
    private javax.swing.JButton Search;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
